image:
  name: atlassian/default-image:3

test: &test
  step:
    name: Test
    script:
      - npm install -g bats
      - chmod a+x test/*.bats
      - bats test/test.bats
    services:
      - docker

pre_release: &pre_release
  step:
    name: Pre release
    image: python:3.7
    script:
      - pip install semversioner
      - ENV=dev bash bump-version.sh
      - pipe: atlassian/bitbucket-pipe-release:5.3.2
        variables:
          REGISTRY_USERNAME: $DOCKER_HUB_USERNAME
          REGISTRY_PASSWORD: $DOCKER_HUB_PASSWORD
          IMAGE: scribesecurity/$BITBUCKET_REPO_SLUG
          VERSION: dev-latest
          TAG: 'false'
          GIT_PUSH: 'false'
    services:
      - docker

release_tag: &release_tag
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:

mirror_sync: &mirror_sync
  step:
    name: Mirror Sync
    image: alpine/git:latest
    script:
      - git clone --bare git@bitbucket.org:scribe-security/valint-pipe.git
      - cd valint-pipe.git
      - git push --mirror git@github.com:scribe-security/valint-pipe.git
    services:
      - docker


release_tag: &release_tag
  step:
    name: Release bump version
    image: python:3.7
    script:
      # - pip install semversioner
      # - bash bump-version.sh
      - pipe: atlassian/bitbucket-pipe-release:5.3.2
        variables:
          REGISTRY_USERNAME: $DOCKER_HUB_USERNAME
          REGISTRY_PASSWORD: $DOCKER_HUB_PASSWORD
          IMAGE: scribesecurity/$BITBUCKET_REPO_SLUG
    services:
      - docker

pipelines:
  default:
    - <<: *test
    # - <<: *mirror_sync
  # branches:
  #   master:
  #     - <<: *test
  #     - <<: *release_tag
  custom:

    push-dev:
      - <<: *pre_release
    release_tag:
      - <<: *release_tag