image: scribesecuriy.jfrog.io/scribe-docker-public-local/scribe_bitbucket:latest
repository: https://www.github.com/scribe-security/bitbucket-pipe
variables:
  command_name:
    required: true
    type: string
  version:
    required: true
    type: boolean
tags:
  - scribe
  - gensbom
  - valint
