name: Mirroring

on: 
  push:
    tags:
      - '*'
    branches:
      - master
  workflow_dispatch:
  # pull_request:


jobs:
  mirror_git:
    runs-on: ubuntu-latest
    steps:                                             
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror bitbucket
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@bitbucket.org:scribe-security/valint-pipe.git
          ssh_private_key:                           
            ${{ secrets.BITBUCKET_SSH_KEY }}

      # - name: Mirror gitlab
      #   uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     target_repo_url:
      #       git@gitlab.com:scribe-test/integrations.git
      #     ssh_private_key:                           
      #       ${{ secrets.BITBUCKET_SSH_KEY }}


              