name: release pipe

env:
  ARTIFACTORY_URL: "https://scribesecuriy.jfrog.io"
  RELEASE_ARTIFACTORY_USERNAME: mikey@scribesecurity.com

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
    
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ARTIFACTORY_URL }}
          username: ${{ secrets.RELEASE_ARTIFACTORY_USERNAME }}
          password: ${{ secrets.RELEASE_ARTIFACTORY_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            scribesecuriy.jfrog.io/scribe-docker-public-local/valint-pipe:0.1.0
            scribesecuriy.jfrog.io/scribe-docker-public-local/valint-pipe:${GITHUB_REF#refs/*/}

      - name: Build and push - pre-release
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile_pre
          push: true
          tags: | 
            scribesecuriy.jfrog.io/scribe-docker-public-local/valint-pipe:dev-latest
            scribesecuriy.jfrog.io/scribe-docker-public-local/valint-pipe:${GITHUB_REF#refs/*/}


      # - name: Mirror bitbucket
      #   uses: pixta-dev/repository-mirroring-action@v1
      #   with:
      #     target_repo_url:
      #       git@bitbucket.org:scribe-security/valint-pipe.git
      #     ssh_private_key:                           
      #       ${{ secrets.BITBUCKET_SSH_KEY }}